version: '3.8'

services:
  db:
    image: postgres:14
    container_name: lastro_postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - lastro_network

volumes:
  db_data:

networks:
  lastro_network:
    driver: bridge
